# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "175e364496398da74e539b16420b98d8"
name = "shrutistore2"
application_url = "https://YOUR_TUNNEL_URL.ngrok.io"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2024-01"

[[webhooks.subscriptions]]
topics = [ "orders/create" ]
uri = "/webhooks"
[[webhooks.subscriptions]]
topics = [ "orders/cancelled" ]
uri = "/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_orders,write_orders"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
